services:
  cleanbookings.api:
    image: ${DOCKER_REGISTRY-}cleanbookingsapi
    container_name: CleanBookings.Api
    build:
      context: .
      dockerfile: CleanBookings.Api/Dockerfile
    depends_on:
        - cleanbookings-db 

  cleanbookings-db:
    image: postgres:latest
    container_name: CleanBookings.Db
    environment:
        - POSTGRES_DB=bookify
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - ./containers/database:/var/lib/postgresql/data
    ports:
        - 15432:5432 
  
  cleanbookings-idp:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: CleanBookings.Identity
    command: start-dev --import-realm
    environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
        - ./.containers/identity:/opt/keycloak/data
        - ./.files:/opt/keycloak/data/import
    ports:
        - 18080:8080
 
  cleanbookings-seq:
    image: datalust/seq:latest
    container_name: CleanBookings.Seq
    environment:
        - ACCEPT_EULA=Y
        - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
        - 5341:5341
        - 8081:80

